version: '3.9'

services:
  postgres:
    container_name: postgres-securebank
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    command: bash -c "echo \"create database ${DATABASE_NAME};\" >> /docker-entrypoint-initdb.d/init.sql && docker-entrypoint.sh postgres"

    ports:
      - '5432:5432'
    networks:
      - backend

  keycloak:
    container_name: keycloak-securebank
    image: quay.io/keycloak/keycloak:16.1.1
    environment:
      JDBC_PARAMS: useSSL=false
      DB_VENDOR: POSTGRES
      KEYCLOAK_USER: securebank
      KEYCLOAK_PASSWORD: securebank
      DB_PORT: 5432
      DB_ADDR: postgres
      DB_DATABASE: ${DATABASE_NAME}
      DB_USER: '${DATABASE_USER}'
      DB_SCHEMA: public
      DB_PASSWORD: '${DATABASE_PASSWORD}'
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
      PROXY_ADDRESS_FORWARDING: 'true'
    depends_on:
      - postgres
    ports:
      - '8080:8080'
      - '8443:8443'
      - '8787:8787'
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    name: backend
    driver: bridge
